version: '3.3'
services:
    alist:
        restart: always
        volumes:
            - alist:/opt/alist/data
            - aria2:/opt/alist/data/temp/aria2
        ports:
            - '5244:5244'
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        container_name: Alist
        image: 'xhofe/alist-aria2:latest'
volumes:
  Alist:
    size: 5Gi
