name: 自动部署okteto

#
on:
  # 仓库触发工作流
  repository_dispatch:
  # 编辑文件触发开始编译
  push:
    paths:
      - 'docker-compose.yaml'
  # 手动触发工作流
  workflow_dispatch:
    inputs:
      build:
        description: 'build proxypool'
        required: true
        default: 'build proxypool'
  # 定时触发编译(每天早5点)
  schedule:
     - cron: '0 21 * * *'
  # 点☆Star触发开始编译
  watch:
     types: [started]
     

#
jobs:
  build:
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    # 运行步骤
    steps:
    
    #
    - name: 准备完毕
      uses: actions/checkout@v2
    
    - name: 登录okteto
      uses: okteto/login@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "激活命名空间"
      uses: okteto/namespace@latest
      
    - name: "创建 stack"
      uses: okteto/deploy-stack@latest
      with:
        build: "true"
