name: 自动部署okteto

#
on:
  # 仓库触发工作流
  repository_dispatch:
  # 编辑文件触发开始编译
  push:
    paths:
      - 'docker-compose.yaml'
  # 手动触发工作流
  workflow_dispatch:
    inputs:
      build:
        description: 'build proxypool'
        required: true
        default: 'build proxypool'
  # 定时触发编译(每天早5点)
  schedule:
     - cron: '0 11,23 * * ?'
  # 点☆Star触发开始编译
  watch:
     types: [started]
     

#
jobs:
  build:
    # 选择虚拟环境
    runs-on: ubuntu-latest
    
    # 运行步骤
    steps:
    
    #
    - name: "准备完毕"
      uses: actions/checkout@v2
    
    - name: "登录+选择命名空间"
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        namespace: html5syt
  
    
    - name: "重新部署"
      uses: okteto/deploy-stack@latest
      
    - name: 保活Checkout
      uses: actions/checkout@v2
    - name: 获取时间
      run: echo "TIME=$(date)" >> $GITHUB_ENV
    - name: Append time to log.txt
      run: echo ${{ env.TIME }} >> log.txt
    - name: 完成保活
      run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add log.txt
          git commit -m "日志，保活"
          git push origin master
